Refactor component to use new tokens, and component dependencies
selsa-inube/inubekit-textfield pull request #3
Opened 2024-02-29 16:26 UTC by JanuarAsprilla

In this card the component is refactored to use the new tokens and dependencies.

2024-03-01 23:48 UTC, wfercanas requested changes

2024-03-01 23:48 UTC, wfercanas commented on src/Textfield/index.tsx
Change interface to `ITextfield`

2024-03-01 23:48 UTC, wfercanas commented on src/Textfield/styles.js
When the textfield is just about to be used, the border is gray, not dark.
Check your styles to see if the error is here. If the problem is with the tokens in foundations, report it to @wfercanas .
Storybook:
![image](https://github.com/selsa-inube/inubekit-textfield/assets/36939686/9cc39444-2a83-4029-af57-fc3ba27f1f06)
Figma:
![image](https://github.com/selsa-inube/inubekit-textfield/assets/36939686/4d0c015e-0b4a-4096-946e-9ddce694d780)

2024-03-01 23:48 UTC, wfercanas commented on src/Textfield/index.tsx
Refactor the Message component. 
1. We had the option of rendering both an error or success message, but now the message will only be used in case of an error
2. The message is also not displayed in a disabled texfield, since there is no way a user can add or change a value when the input cannot be modified.

With this refactor perhaps we can delete the Message component altogether and add the markup inside the return of Textfield itself.

2024-03-01 23:48 UTC, wfercanas commented on src/Textfield/index.tsx
The (Requerido) text right next to the label now should always have a danger appearance:
Storybook:
![image](https://github.com/selsa-inube/inubekit-textfield/assets/36939686/b8f6682d-fbe0-42f0-a711-37e8ec361edc)

Figma:
![image](https://github.com/selsa-inube/inubekit-textfield/assets/36939686/1e3af4d9-8f1f-44c1-9dde-54b55dfd2fd0)

2024-03-01 23:48 UTC, wfercanas commented on src/Textfield/styles.js
There must be a gap of 4px between the container of the input and the message in figma:
![image](https://github.com/selsa-inube/inubekit-textfield/assets/36939686/69fdd2c7-9c9b-4032-8e97-c04d6119c0b0)

2024-03-01 23:48 UTC, wfercanas commented on src/Textfield/index.tsx
The component no longer supports the readOnly prop. Adjust the prop in index.tsx and props.ts.
This is what happens when we currently set readOnly to true in storybook:

![image](https://github.com/selsa-inube/inubekit-textfield/assets/36939686/6158c058-34ba-4189-b443-1599bd4ae773)

2024-03-04 16:22 UTC, cmarin001 requested changes

2024-03-04 16:22 UTC, cmarin001 commented on src/Textfield/index.tsx
> +const Message = (props: Omit<ITextfield, "id"> & { message?: string }) => {
It may be beneficial to reconsider the inclusion of this component. I recommend reviewing the implementation details provided in the textarea PR for a potentially more effective approach.

2024-03-04 18:46 UTC, cmarin001 requested changes

2024-03-04 18:46 UTC, cmarin001 commented on package.json
> +    "@inubekit/foundations": "^2.4.0",
I would be a good idea to use the latest version

2024-03-04 21:00 UTC, cmarin001 requested changes

2024-03-05 14:04 UTC, cmarin001 requested changes

2024-03-05 14:04 UTC, cmarin001 commented on src/Textfield/styles.js
> +      theme?.text?.gray?.content?.color?.regular ||
still using text-token when it should be input tokens

2024-03-05 14:04 UTC, cmarin001 commented on src/Textfield/styles.js
>      if ($disabled) {
This snippet is no longer necessary, as messages cannot be disabled; they only appear in the event of an error

2024-03-05 22:40 UTC, wfercanas commented on src/Textfield/styles.js
>    background-color: ${$setBackgroundColor};
Instead of using a function, you can get the disabled prop and decide with a ternary the token to use.

2024-03-05 22:41 UTC, wfercanas commented on src/Textfield/styles.js
>    background-color: ${$setBackgroundColor};
This property has the same problem with the use of this function. Refactor to use a ternary with the disabled prop

2024-03-07 02:49 UTC, wfercanas requested changes

2024-03-07 02:49 UTC, wfercanas commented on src/Textfield/stories/Textfield.stories.tsx
>  Default.args = {
This object still passes the `readOnly` prop to the component

2024-03-07 02:49 UTC, wfercanas commented on src/Textfield/index.tsx
> +      onFocus && onBlur?.(e);
1. There is no point about checking if `onFocus` is defined to then execute `onBlur`, they are separate things.
2. If you originally check `onBlur`, then the `?` is not necessary, since the function call is done with an existing `onBlur`. Any other error is catched by the `try..catch`

2024-03-07 02:49 UTC, wfercanas commented on src/Textfield/index.tsx
> +      onFocus && onFocus?.(e);
There is no necessary to check `onFocus` with `?`

2024-03-07 14:22 UTC, JanuarAsprilla commented on src/Textfield/stories/Textfield.stories.tsx
>  Default.args = {
solved

2024-03-07 14:22 UTC, JanuarAsprilla commented on src/Textfield/index.tsx
> +      onFocus && onFocus?.(e);
solved

2024-03-07 14:22 UTC, JanuarAsprilla commented on src/Textfield/index.tsx
> +      onFocus && onBlur?.(e);
solved

2024-03-08 21:57 UTC, wfercanas requested changes
We're missing "react-icons/ms" in vite.config.ts (external array).

2024-03-11 17:08 UTC, wfercanas requested changes

2024-03-11 17:08 UTC, wfercanas commented on vite.config.ts
> +        "react-icons/ms",
Perdón, es "react-icons/md". Se me fue la 's'

2024-03-11 17:23 UTC, JanuarAsprilla commented on vite.config.ts
> +        "react-icons/ms",
solved

2024-03-11 23:29 UTC, wfercanas approved these changes

2024-03-11 23:29 UTC, merged